services:
  # ----------------------------------------------------------------------
  # Service: PostgreSQL-Datenbank
  # ----------------------------------------------------------------------
  postgres:
    image: postgres:16-alpine # Spezifische, schlanke Version für Konsistenz und Effizienz
    container_name: dev_postgres_db # Eindeutiger Name für den Container

    environment:
      # Essentielle Umgebungsvariablen für die PostgreSQL-Initialisierung
      POSTGRES_DB: jpa_db         # Dein gewünschter Datenbankname (für Anwendungen)
      POSTGRES_USER: devuser           # Dein Datenbank-Benutzername
      POSTGRES_PASSWORD: devpassword   # Dein Datenbank-Passwort (nur für Entwicklungsumgebung!)

    ports:
      - "5432:5432" # Mappt den Standard-DB-Port auf deinen Host.

    volumes:
      # WICHTIG: Persistente Speicherung der Datenbankdaten.
      # "postgres_data" ist ein benanntes Volume, das von Docker verwaltet wird.
      - postgres_data_jpa:/var/lib/postgresql/data

    shm_size: 256mb # Erhöht das Shared Memory für bessere PostgreSQL-Performance (z.B. 256MB ist ein guter Startwert)

    healthcheck: # Optional, aber sehr nützlich: Prüft, ob die DB wirklich bereit ist
      test: ["CMD-SHELL", "pg_isready -U devuser -d jpa_db"]
      interval: 5s
      timeout: 5s
      retries: 5

# ----------------------------------------------------------------------
# Definition der benannten Volumes
# ----------------------------------------------------------------------
volumes:
  postgres_data_jpa: # Dieses Volume wird die Daten für den PostgreSQL-Container speichern
